# -*- coding: utf-8 -*-
"""EDA_Autos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1buimueQPtQd3g8C-_1YPvJNfZFfuTZVZ
"""

import pandas as pd
import matplotlib.pyplot as plt

au = pd.read_excel('/content/Consumo Gasolina Autos Ene 2018.xlsx')

"""Buscardor de **Submarcas** por **Marca**"""

au[au.Marca == 'VW'].Submarca.unique()

au.Marca.unique()

au.columns

min = au['Potencia (HP)'].min()
max = au['Potencia (HP)'].max()
media = au['Potencia (HP)'].mean()
print('Min = ', min,'\t', 'Max = ',max,'\t', 'Mean = ',media)

au['Potencia (HP)'].describe()

#CONTEMOS LOS NULOS
au.isnull().sum()

"""COMPARATIVA ENTRE EL **VW VENTO, KIA RIO, CHEVROLET CAVALIER, NISSAN SENTRA** \\
Caja Manual a gasolina
"""

modelos = ['VENTO', 'RIO', 'CAVALIER', 'SENTRA']

maxim = au.groupby(['Marca']).Modelo.max(); maxim

vw = au[au.Marca == 'VW']
vw_vento = vw[vw.Submarca == 'VENTO']

vw_vento.loc[(vw_vento['Trans.']=='MAN') & (vw_vento['Comb.']=='Gasolina')]

kia = au[au.Marca == 'KIA']
kia

au.Cilindros.value_counts()
Ejey=list(au.Cilindros.value_counts())
Ejex=list(au.Cilindros.value_counts().index)
plt.pie(Ejey, labels=Ejex)
plt.show()

p = au.Cilindros.value_counts().map(lambda x : str(round(x*(100/sum(Ejey)),2))+' %')
p